name = { (!"\n" ~ !ASCII_DIGIT+ ~ ANY)+ }

separator = _{ (" " | "\t")+ }

decimal = _{ sign? ~ number ~ ("." ~ number ~ ("E" ~ sign ~ number)?)? }
sign = _{ "+" | "-" }
number = _{ ASCII_DIGIT+ }

file = { SOI ~ (ring ~ NEWLINE)* ~ "END" ~ NEWLINE* ~ EOI }

ring = { (name ~ NEWLINE)? ~ subtract? ~ number ~ NEWLINE ~ (point ~ NEWLINE)* ~ "END" }
subtract = { "!" }
point = { separator? ~ x ~ separator ~ y}
x = { decimal }
y = { decimal }
